### Add a New Post
POST http://localhost:3000/api/posts 
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "owner": "michal"
}
### Get All Posts
GET http://localhost:3000/api/posts
###Get post by Id
GET http://localhost:3000/api/posts/6739d3d6342061c73896d574

