### Add a New Post
POST http://localhost:3000/api/posts 
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "senderId": "1235"
}
### Get All Posts
GET http://localhost:3000/api/getposts
###Get post by Id
GET http://localhost:3000/api/posts/673a13dd7b94e5067bea5be9
###Get post by sender Id
GET http://localhost:3000/api/posts?sender=124



